services:
  # Service principal Next.js
  web:
    pull-policy: always
    image: beukernoot/portfolio:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    networks:
      - npm_default
    depends_on:
      - postgres

  # Service PostgreSQL (pour futures fonctionnalités)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portfolio_db}
      POSTGRES_USER: ${POSTGRES_USER:-boris}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - npm_default

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: npm_default